---
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    assignees:
      - maheshrjl
    reviewers:
      - maheshrjl
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
