name: ci 
on:
  push:
    branches:
      - main
      - source
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
#         with:
#           fetch-depth: 0
          
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
          
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force
